CREATE 
	OR REPLACE PROCEDURE SP_INSERT_AND_LIST_PRODUCTS ( NOMBRE VARCHAR2, FEC_REGISTRO DATE, SRC OUT SYS_REFCURSOR, CODIGO_RPTA OUT NUMBER, MENSAJE_RPTA OUT VARCHAR2 ) AS 
	BEGIN
		INSERT INTO PRODUCTO ( NOMBRE, FEC_REGISTRO ) VALUES ( NOMBRE, FEC_REGISTRO ); 
		COMMIT;
		OPEN SRC FOR SELECT ID_PRODUCTO, NOMBRE, TO_CHAR( FEC_REGISTRO, 'YYYYMMDD' ) AS FEC_REGISTRO FROM PRODUCTO WHERE TO_CHAR( FEC_REGISTRO, 'YYYYMMDD' ) = TO_CHAR( SYSDATE, 'YYYYMMDD' );
		CODIGO_RPTA := 0;
		MENSAJE_RPTA := 'Ejecucion con exito';
	EXCEPTION
		WHEN OTHERS THEN
			CODIGO_RPTA := 1;
			MENSAJE_RPTA := SQLCODE || SQLERRM;
END;