server:
  port: ${PORT:8080}
spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 300000
      idle-timeout: 100000
      max-lifetime: 1800000
      minimum-idle: 2
  hateoas:
    use-hal-as-default-json-media-type: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
  password: xBrecumax25%
  username: gh